name: Bug report
description: File a bug report
title: "[BUG] <short description>"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do we reproduce the issue?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: FerriteDB version
      description: Run `ferrite --version`
