name: Feature request
description: Suggest an idea or enhancement
title: "[FEATURE] <short description>"
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: What's the user-facing need or use case?
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: What's the benefit?
      description: How does this improve FerriteDB?
