[package]
name = "ferrite-db"
version = "0.3.0"
edition = "2024"

[dependencies]
sqlparser = "0.41"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
lazy_static = "1.4"
